<a href="https://colab.research.google.com/github/simon-win/simon/blob/master/%ED%95%99%EC%8A%B5%EC%9D%B4_%EC%9E%98_%EB%90%98%EB%8A%94_%EB%AA%A8%EB%8D%B8_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

학습이 잘 되는 모델
사용할 레이어

tf.keras.layers.BatchNormalization()
tf.keras.layers.Activation('swish')
데이터

보스턴 집값 예측: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv

아이리스 품종 분류: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv


In [1]:
import tensorflow as tf
import pandas as pd

In [3]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [5]:
print(아이리스.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


In [4]:
print(아이리스.shape)

(150, 5)


In [7]:
#원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [10]:
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [11]:
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor',
       '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [14]:
x = tf.keras.layers.Input(shape=[4])
h = tf.keras.layers.Dense(8, activation='swish')(x)
h = tf.keras.layers.Dense(8, activation='swish')(h)
h = tf.keras.layers.Dense(8, activation='swish')(h)
y = tf.keras.layers.Dense(3, activation='softmax')(h)
model = tf.keras.models.Model(x, y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [18]:
x = tf.keras.layers.Input(shape=[4])

h = tf.keras.layers.Dense(8)(x)
h = tf.keras.layers.BatchNormalization()(h)
h = tf.keras.layers.Activation('swish')(h)

h = tf.keras.layers.Dense(8)(x)
h = tf.keras.layers.BatchNormalization()(h)
h = tf.keras.layers.Activation('swish')(h)

h = tf.keras.layers.Dense(8)(x)
h = tf.keras.layers.BatchNormalization()(h)
h = tf.keras.layers.Activation('swish')(h)

y = tf.keras.layers.Dense(3, activation='softmax')(h)
model = tf.keras.models.Model(x, y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [20]:
model.fit(독립, 종속, epochs=1000)

Epoch 1/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0736 - accuracy: 0.9667
Epoch 2/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.2404 - accuracy: 0.9000
Epoch 3/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0638 - accuracy: 0.9800
Epoch 4/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.1166 - accuracy: 0.9533
Epoch 5/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.1386 - accuracy: 0.9267
Epoch 6/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0658 - accuracy: 0.9933
Epoch 7/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.1037 - accuracy: 0.9467
Epoch 8/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.1759 - accuracy: 0.9133
Epoch 9/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.1252 - accuracy: 0.9467
Epoch 10/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1095 - accuracy: 0.9533
Epoch 11/1000
5/5 [

In [21]:
model.get_weights()

[array([[ 0.21822645, -0.64066404,  0.14044324,  0.04171343, -0.40389252,
         -0.1726541 ,  0.19572264,  0.10650062],
        [ 0.38686144, -0.20471714, -0.27322978, -0.14650032, -0.4397879 ,
         -0.40308017,  0.36474794, -0.27098098],
        [-0.6930568 ,  0.14350398,  1.4221134 ,  1.0623003 ,  0.28688505,
          0.60793626, -0.56209064,  0.33906305],
        [-0.6328346 ,  0.33533815,  0.71068627,  0.45845714,  0.6158555 ,
          0.02513359, -0.61843574, -0.8221821 ]], dtype=float32),
 array([-0.00658772, -0.02452554,  0.00488271,  0.04518656,  0.08450926,
         0.10577489, -0.00150579,  0.03837743], dtype=float32),
 array([2.5769238, 0.8680613, 1.7937486, 1.7950174, 1.8043647, 1.8130754,
        3.105175 , 1.418274 ], dtype=float32),
 array([-0.71003765,  1.138871  ,  0.13400453, -0.34897134, -0.19336681,
        -0.41097736, -0.4550688 ,  1.484186  ], dtype=float32),
 array([-0.86725444, -3.4546647 ,  6.162421  ,  4.3178086 , -1.7944151 ,
         0.17387317, -0